version: 2

sources:
  - name:
    description: "" # can use markdown file here
    freshness: # default freshness
      warn_after: {count: 12, period: hour}
      error_after: {count: 24, period: hour}
    loaded_at_field: _etl_loaded_at

    database: ""
    schema: ""
    tables:
      - name: ""
        description: ""
        columns:
          - name: ""
            description: ""

      - name: example
        description: ""
        tests:
          # row count
          - source_rowcount:
          # table column validation
          - raw_column_existence:
          - dbt_expectations.expect_table_columns_to_contain_set:
              column_list: ["<col list here>"]
          # similar to the above - but the above is more succinct
          - dbt_expectations.expect_table_column_count_to_equal:
          # string matching
          - dbt_expectations.expect_column_value_lengths_to_be_between:
          # other - good candidae use
          - dbt_expectations.expect_column_min_to_be_between:
          - dbt_expectations.expect_column_max_to_be_between:
          # other - less of a candidate use
          - dbt_expectations.expect_row_values_to_have_recent_data:
          - dbt_expectations.expect_grouped_row_values_to_have_recent_data:
          - dbt_expectations.expect_table_row_count_to_equal_other_table_times_factor:

        columns:
          - name: <col name>
            description: ""

models:
