
version: 2

models:
  - name: my_first_dbt_model
    # 1 - Docs Blocks
    description: '{{ doc("first_model") }}'
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: my_second_dbt_model
    description: '{{ doc("pf_second_example") }}'
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

exposures:
  - name: pf_exposure_example
    # type can be 1 of 5:
    # dashboard, notebook, analysis, ml, application
    type: dashboard
    url: https://bbc.com
    description: Example description here

    owner:
      name: Claire from Data
      email: data@jaffleshop.com

    # required args:
    # name, type, owner
    # But depends on usually exists too
